### PR TITLE
Feature: Define position in journal

### PR DESCRIPTION
**Pull request by Brazier85**
Added a option to select where in the journal note the tracker info should be added.

Also I changed the Notice function to look a bit nicer.

### CODE REVIEW

**Comment by dartungar** [comment]
@Brazier85 hey, thanks for the PR! I will check it when I have time 🫡

**Comment by dartungar** [comment]
@Brazier85 it seems like if there is another header, this feature doesn't work. Please consider fixing this 😅
bug1

**Comment by Brazier85** [comment]
@dartungar function should be fixed by now.. I made a super stupid mistake :D

**Comment by Brazier85** [comment]
@dartungar I think I got all the possible position errors by now :)

**Review by dartungar — APPROVED** [review]
Looks good now :) TY!

**Pull request merged**
